title: 'csatar.knowledgerepository::lang.plugin.admin.menu.knowledgeRepositoryParameters.accidentRiskLevels'
modelClass: Csatar\KnowledgeRepository\Models\AccidentRiskLevel
toolbar:
    buttons: reorder_toolbar
