list: $/csatar/knowledgerepository/models/accidentrisklevel/columns.yaml
modelClass: Csatar\KnowledgeRepository\Models\AccidentRiskLevel
title: 'csatar.knowledgerepository::lang.plugin.admin.menu.knowledgeRepositoryParameters.accidentRiskLevels'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'csatar/knowledgerepository/accidentrisklevel/update/:id'
