list: $/csatar/knowledgerepository/models/trialsystemtrialtype/columns.yaml
modelClass: Csatar\KnowledgeRepository\Models\TrialSystemTrialType
title: 'csatar.knowledgerepository::lang.plugin.admin.trialSystem.trialSystemTrialTypes'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'csatar/knowledgerepository/trialsystemtrialtypes/update/:id'
