name: 'csatar.knowledgerepository::lang.plugin.admin.menu.knowledgeRepositoryParameters.headCount'
form: $/csatar/knowledgerepository/models/headcount/fields.yaml
modelClass: Csatar\KnowledgeRepository\Models\HeadCount
defaultRedirect: csatar/knowledgerepository/headcount
create:
    redirect: 'csatar/knowledgerepository/headcount/update/:id'
    redirectClose: csatar/knowledgerepository/headcount
update:
    redirect: csatar/knowledgerepository/headcount
    redirectClose: csatar/knowledgerepository/headcount
