list: $/csatar/knowledgerepository/models/headcount/columns.yaml
modelClass: Csatar\KnowledgeRepository\Models\HeadCount
title: 'csatar.knowledgerepository::lang.plugin.admin.menu.knowledgeRepositoryParameters.headCount'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'csatar/knowledgerepository/headcount/update/:id'
