list: $/csatar/csatar/models/foodsensitivity/columns.yaml
modelClass: Csatar\Csatar\Models\FoodSensitivity
title: 'csatar.csatar::lang.plugin.admin.admin.menu.scoutSystemData.foodSensitivityCategories'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'csatar/csatar/foodsensitivities/update/:id'
