name: 'csatar.knowledgerepository::lang.plugin.admin.menu.knowledgeRepositoryParameters.trialSystemTopic'
form: $/csatar/knowledgerepository/models/trialsystemtopic/fields.yaml
modelClass: Csatar\KnowledgeRepository\Models\TrialSystemTopic
defaultRedirect: csatar/knowledgerepository/trialsystemtopics
create:
    redirect: 'csatar/knowledgerepository/trialsystemtopics/update/:id'
    redirectClose: csatar/knowledgerepository/trialsystemtopics
update:
    redirect: csatar/knowledgerepository/trialsystemtopics
    redirectClose: csatar/knowledgerepository/trialsystemtopics
