list: $/csatar/knowledgerepository/models/trialsystemtopic/columns.yaml
modelClass: Csatar\KnowledgeRepository\Models\TrialSystemTopic
title: 'csatar.knowledgerepository::lang.plugin.admin.knowledgeRepository.trialSystems.trialSystemTopics'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'csatar/knowledgerepository/trialsystemtopics/update/:id'
