name: 'csatar.knowledgerepository::lang.plugin.admin.trialSystem.trialSystemTopic'
form: $/csatar/knowledgerepository/models/trialsystemsubtopic/fields.yaml
modelClass: Csatar\KnowledgeRepository\Models\TrialSystemSubtopic
defaultRedirect: csatar/knowledgerepository/trialsystemsubtopics
create:
    redirect: 'csatar/knowledgerepository/trialsystemsubtopics/update/:id'
    redirectClose: csatar/knowledgerepository/trialsystemsubtopics
update:
    redirect: csatar/knowledgerepository/trialsystemsubtopics
    redirectClose: csatar/knowledgerepository/trialsystemsubtopics
