plugin:
    name: 'csatar.knowledgerepository::lang.plugin.name'
    description: 'csatar.knowledgerepository::lang.plugin.description'
    author: CSATÁR
    icon: oc-icon-book
    homepage: ''
navigation:
    main-menu-knowledge-repository:
        label: 'csatar.knowledgerepository::lang.plugin.admin.menu.knowledgeRepository.knowledgeRepository'
        url: /
        icon: icon-book
        permissions:
            - csatar.manage.data
        sideMenu:
            side-menu-games:
                label: 'csatar.knowledgerepository::lang.plugin.admin.menu.knowledgeRepository.games'
                url: /csatar/knowledgerepository/games
                icon: icon-child
                permissions:
                    - csatar.manage.data
            side-menu-songs:
                label: 'csatar.knowledgerepository::lang.plugin.admin.menu.knowledgeRepository.songs'
                url: csatar/knowledgerepository/songs
                icon: icon-music
                permissions:
                    - csatar.manage.data
            side-menu-work-plans:
                label: 'csatar.knowledgerepository::lang.plugin.admin.menu.knowledgeRepository.workPlans'
                url: csatar/knowledgerepository/workplans
                icon: icon-list
                permissions:
                    - csatar.manage.data
            side-menu-methodologies:
                label: 'csatar.knowledgerepository::lang.plugin.admin.menu.knowledgeRepository.methodologies'
                url: csatar/knowledgerepository/methodologies
                icon: icon-paint-brush
                permissions:
                    - csatar.manage.data
            side-menu-trialsystem:
                label: 'csatar.knowledgerepository::lang.plugin.admin.trialSystem.trialSystems'
                url: csatar/knowledgerepository/trialsystems
                icon: icon-cubes
                permissions:
                    - csatar.manage.data
    main-menu-knowledge-repository-parameters:
        label: 'csatar.knowledgerepository::lang.plugin.admin.menu.knowledgeRepositoryParameters.knowledgeRepositoryParameters'
        url: /csatar/knowledgerepository/knowledgeRepositoryparameters
        icon: icon-pencil
        permissions:
            - csatar.manage.data
        sideMenu:
            side-menu-item:
                label: 'csatar.knowledgerepository::lang.plugin.admin.menu.knowledgeRepositoryParameters.gameDevelopmentGoals'
                url: csatar/knowledgerepository/gamedevelopmentgoals
                icon: icon-sliders
                permissions:
                    - csatar.manage.data
            side-menu-item2:
                label: 'csatar.knowledgerepository::lang.plugin.admin.menu.knowledgeRepositoryParameters.accidentRiskLevels'
                url: csatar/knowledgerepository/accidentrisklevel
                icon: icon-bolt
                iconSvg: ''
                permissions:
                    - csatar.manage.data
            side-menu-tools:
                label: 'csatar.knowledgerepository::lang.plugin.admin.menu.knowledgeRepositoryParameters.tools'
                url: csatar/knowledgerepository/tools
                icon: icon-bullhorn
                permissions:
                    - csatar.manage.data
            side-menu-headcount:
                label: 'csatar.knowledgerepository::lang.plugin.admin.menu.knowledgeRepositoryParameters.headCounts'
                url: csatar/knowledgerepository/headcounts
                icon: icon-group
                permissions:
                    - csatar.manage.data
            side-menu-duration:
                label: 'csatar.knowledgerepository::lang.plugin.admin.menu.knowledgeRepositoryParameters.durations'
                url: csatar/knowledgerepository/durations
                icon: icon-clock-o
                permissions:
                    - csatar.manage.data
            side-menu-location:
                label: 'csatar.knowledgerepository::lang.plugin.admin.menu.knowledgeRepositoryParameters.locations'
                url: csatar/knowledgerepository/locations
                icon: icon-map-marker
                permissions:
                    - csatar.manage.data
            side-menu-gametype:
                label: 'csatar.knowledgerepository::lang.plugin.admin.menu.knowledgeRepositoryParameters.gameTypes'
                url: csatar/knowledgerepository/gametypes
                icon: icon-gamepad
                permissions:
                    - csatar.manage.data
            side-menu-methodology-type:
                label: 'csatar.knowledgerepository::lang.plugin.admin.menu.knowledgeRepositoryParameters.methodologyType'
                url: csatar/knowledgerepository/methodologytypes
                icon: icon-tag
            side-menu-trialsystemcategory:
                label: 'csatar.knowledgerepository::lang.plugin.admin.trialSystem.trialSystemCategories'
                url: csatar/knowledgerepository/trialsystemcategories
                icon: icon-cubes
                permissions:
                    - csatar.manage.data
            side-menu-trialsystemtopics:
                label: 'csatar.knowledgerepository::lang.plugin.admin.trialSystem.trialSystemTopics'
                url: csatar/knowledgerepository/trialsystemtopics
                icon: icon-cubes
                permissions:
                    - csatar.manage.data
            side-menu-trialsystemsubtopics:
                label: 'csatar.knowledgerepository::lang.plugin.admin.trialSystem.trialSystemSubTopics'
                url: csatar/knowledgerepository/trialsystemsubtopics
                icon: icon-cubes
                permissions:
                    - csatar.manage.data
            side-menu-trialsystemtypes:
                label: 'csatar.knowledgerepository::lang.plugin.admin.trialSystem.trialSystemTypes'
                url: csatar/knowledgerepository/trialsystemtypes
                icon: icon-cubes
                permissions:
                    - csatar.manage.data
            side-menu-trialsystemtrialtypes:
                label: 'csatar.knowledgerepository::lang.plugin.admin.trialSystem.trialSystemTrialTypes'
                url: csatar/knowledgerepository/trialsystemtrialtypes
                icon: icon-cubes
                permissions:
                    - csatar.manage.data
