plugin:
    name: 'csatar.forms::lang.plugin.name'
    description: 'csatar.forms::lang.plugin.description'
    author: 'csatar.forms::lang.plugin.author'
    icon: oc-icon-file-text
    homepage: ''
navigation:
    main-menu-item:
        label: Forms
        url: csatar/forms/forms
        icon: icon-paperclip
        permissions:
            - csatar.manage.forms
        sideMenu:
            forms-menu-item:
                label: Forms
                url: csatar/forms/forms
                icon: icon-file-text-o
                permissions:
                    - csatar.manage.forms
permissions:
    csatar.manage.forms:
        tab: 'csatar.forms::lang.plugin.name'
        label: 'csatar.forms::lang.plugin.permissions.manageForms'
