title: 'csatar.knowledgerepository::lang.plugin.admin.menu.knowledgeRepositoryParameters.gameDevelopmentGoals'
modelClass: Csatar\KnowledgeRepository\Models\GameDevelopmentGoal
toolbar:
    buttons: reorder_toolbar
