list: $/csatar/csatar/models/membershipcardrequest/columns.yaml
modelClass: Csatar\Csatar\Models\MembershipCardRequest
title: 'csatar.csatar::lang.plugin.admin.membershipCard.requests'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
