list: $/csatar/knowledgerepository/models/location/columns.yaml
modelClass: Csatar\KnowledgeRepository\Models\Location
title: 'csatar.knowledgerepository::lang.plugin.admin.menu.knowledgeRepositoryParameters.locations'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'csatar/knowledgerepository/locations/update/:id'
