list: $/csatar/csatar/models/membershipcard/columns.yaml
modelClass: Csatar\Csatar\Models\MembershipCard
title: 'csatar.csatar::lang.plugin.admin.membershipCard.membershipCards'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'csatar/csatar/membershipcards/update/:id'
defaultSort:
    column: team_number
    direction: asc
