list: $/csatar/csatar/models/dynamicfields/columns.yaml
modelClass: Csatar\Csatar\Models\DynamicFields
title: 'csatar.csatar::lang.plugin.admin.dynamicFields.dynamicFields'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'csatar/csatar/dynamicfields/update/:id'
