game_development_goals:
  deferredBinding: true
  label: 'csatar.knowledgerepository::lang.plugin.admin.menu.knowledgeRepositoryParameters.gameDevelopmentGoal'
  view:
    list: $/csatar/knowledgerepository/models/gamedevelopmentgoal/columns.yaml
    toolbarButtons: add|remove|create
  manage:
    list: $/csatar/knowledgerepository/models/gamedevelopmentgoal/columns.yaml
    form: $/csatar/knowledgerepository/models/gamedevelopmentgoal/fields.yaml

tools:
  deferredBinding: true
  label: 'csatar.knowledgerepository::lang.plugin.admin.menu.knowledgeRepositoryParameters.tool'
  view:
    list: $/csatar/knowledgerepository/models/tool/columns.yaml
    toolbarButtons: add|remove|create
  manage:
    list: $/csatar/knowledgerepository/models/tool/columns.yaml
    form: $/csatar/knowledgerepository/models/tool/fields.yaml

headcounts:
  deferredBinding: true
  label: 'csatar.knowledgerepository::lang.plugin.admin.menu.knowledgeRepositoryParameters.headCount'
  view:
    list: $/csatar/knowledgerepository/models/headcount/columns.yaml
    toolbarButtons: add|remove|create
  manage:
    list: $/csatar/knowledgerepository/models/headcount/columns.yaml
    form: $/csatar/knowledgerepository/models/headcount/fields.yaml

durations:
  deferredBinding: true
  label: 'csatar.knowledgerepository::lang.plugin.admin.menu.knowledgeRepositoryParameters.duration'
  view:
    list: $/csatar/knowledgerepository/models/duration/columns.yaml
    toolbarButtons: add|remove|create
  manage:
    list: $/csatar/knowledgerepository/models/duration/columns.yaml
    form: $/csatar/knowledgerepository/models/duration/fields.yaml

age_groups:
  deferredBinding: true
  label: 'csatar.csatar::lang.plugin.admin.ageGroups.ageGroups'
  view:
    list: $/csatar/csatar/models/agegroup/columns.yaml
    toolbarButtons: add|remove|create
  manage:
    list: $/csatar/csatar/models/agegroup/columns.yaml
    form: $/csatar/csatar/models/agegroup/fields.yaml

locations:
  deferredBinding: true
  label: 'csatar.knowledgerepository::lang.plugin.admin.menu.knowledgeRepositoryParameters.location'
  view:
    list: $/csatar/knowledgerepository/models/location/columns.yaml
    toolbarButtons: add|remove|create
  manage:
    list: $/csatar/knowledgerepository/models/location/columns.yaml
    form: $/csatar/knowledgerepository/models/location/fields.yaml

game_types:
  deferredBinding: true
  label: 'csatar.knowledgerepository::lang.plugin.admin.menu.knowledgeRepositoryParameters.gameType'
  view:
    list: $/csatar/knowledgerepository/models/gametype/columns.yaml
    toolbarButtons: add|remove|create
  manage:
    list: $/csatar/knowledgerepository/models/gametype/columns.yaml
    form: $/csatar/knowledgerepository/models/gametype/fields.yaml
