name: 'csatar.knowledgerepository::lang.plugin.admin.trialSystem.trialSystemType'
form: $/csatar/knowledgerepository/models/trialsystemtype/fields.yaml
modelClass: Csatar\KnowledgeRepository\Models\TrialSystemType
defaultRedirect: csatar/knowledgerepository/trialsystemtypes
create:
    redirect: 'csatar/knowledgerepository/trialsystemtypes/update/:id'
    redirectClose: csatar/knowledgerepository/trialsystemtypes
update:
    redirect: csatar/knowledgereposito