list: $/csatar/knowledgerepository/models/trialsystemtype/columns.yaml
modelClass: Csatar\KnowledgeRepository\Models\TrialSystemType
title: 'csatar.knowledgerepository::lang.plugin.admin.trialSystem.trialSystemTypes'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'