list: $/csatar/knowledgerepository/models/methodologytype/columns.yaml
modelClass: Csatar\KnowledgeRepository\Models\MethodologyType
title: 'csatar.knowledgerepository::lang.plugin.admin.menu.knowledgeRepositoryParameters.methodologyTypes'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'csatar/knowledgerepository/methodologytypes/update/:id'
